version: '3.9'

services:
  app:
    container_name: safe-edu-frontend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_SERVER=${NEXT_PUBLIC_API_SERVER:-https://safe-edu.fuses.fun}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL:-http://localhost:3000}
      - NEXT_PUBLIC_DSN_SENTRY=${NEXT_PUBLIC_DSN_SENTRY}
      - NEXT_PUBLIC_DOMAIN_IMAGE=${NEXT_PUBLIC_DOMAIN_IMAGE:-tekup-dev.s3.amazonaws.com}
      - NEXT_PUBLIC_ASSETS_URL=${NEXT_PUBLIC_ASSETS_URL:-https://motomo-api.tekup.vn/static}
      - NEXT_PUBLIC_FIREBASE_KEY_PAIR=${NEXT_PUBLIC_FIREBASE_KEY_PAIR}
      - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
      - NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - '3002:3002'
    restart: unless-stopped
    networks:
      - safe-edu-network

networks:
  safe-edu-network:
    driver: bridge