"use client";

import card_image_1 from "@img/images/library/card_image_1.png";
import card_image_2 from "@img/images/library/card_image_2.png";
import card_image_3 from "@img/images/library/card_image_3.png";
import card_image_4 from "@img/images/library/card_image_4.png";

import { User, Library } from "./types";
export const users: User[] = [
  {
    id: "9953ed85-31a0-4db9-acc8-e25b76176443",
    userName: "John Miller",
    phone: "+1-555-0101",
    email: "john.miller@example.com",
    role: "client",
    status: "inactive",
    location: "4306 Highland Drive, Seattle, WA 98109",
    image: "john.miller.jpg",
    rtn: "US2347908701",
    otherInformation: "John Miller works in a tech startup in Seattle.",
    createdAt: new Date("2024-02-07T23:35:52.087Z"),
    updatedAt: new Date("2024-02-07T23:38:03.259Z"),
  },
  {
    id: "328c2bef-d84b-44a2-b5ae-03bd6550c4c4",
    userName: "Elizabeth Smith",
    phone: "+44-020-8102",
    email: "elizabeth.smith@example.co.uk",
    role: "client",
    status: "active",
    location: "22 Camden Road, London, NW1 9DP",
    image: "elizabeth.smith.jpg",
    rtn: "UK6574829302",
    otherInformation:
      "Elizabeth Smith works in a financial consultancy in London.",
    createdAt: new Date("2024-02-07T23:35:52.087Z"),
    updatedAt: new Date("2024-02-07T23:38:03.259Z"),
  },
  {
    id: "9543e3a4-99f2-4fcb-ba5d-f2aaebff6716",
    userName: "Noah Wilson",
    phone: "+61-8-9200-1234",
    email: "noah.wilson@example.com.au",
    role: "provider",
    status: "inactive",
    location: "305 Murray Street, Perth, WA 6000",
    image: "noah.wilson.jpg",
    rtn: "AU9085471203",
    otherInformation:
      "Noah Wilson is involved in the mining industry in Perth.",
    createdAt: new Date("2024-02-07T23:35:52.087Z"),
    updatedAt: new Date("2024-02-07T23:38:03.259Z"),
  },
  {
    id: "bdcba306-57fa-4722-82e3-c4933b09e69b",
    userName: "Marie Dubois",
    phone: "+33-1-4533-0012",
    email: "marie.dubois@example.fr",
    role: "client",
    status: "active",
    location: "14 Rue de Rivoli, 75004 Paris",
    image: "marie.dubois.jpg",
    rtn: "FR21340987201",
    otherInformation: "Marie Dubois works in a fashion house in Paris.",
    createdAt: new Date("2024-02-07T23:35:52.087Z"),
    updatedAt: new Date("2024-02-07T23:38:03.259Z"),
  },
  {
    id: "e643dbea-0ab2-4d3d-8bb8-63aedf027a66",
    userName: "Wang Wei",
    phone: "+86-20-8221-1234",
    email: "wang.wei@example.com.cn",
    role: "client",
    status: "inactive",
    location: "206 Huanshi E Rd, Yuexiu District, Guangzhou, Guangdong",
    image: "wang.wei.jpg",
    rtn: "CN9988321221",
    otherInformation:
      "Wang Wei works for an electronics manufacturing company in Guangzhou.",
    createdAt: new Date("2024-02-07T23:35:52.087Z"),
    updatedAt: new Date("2024-02-07T23:38:03.259Z"),
  },
  {
    id: "94093200-c89f-410f-ba96-046f33fabb3e",
    userName: "Conor Murphy",
    phone: "+353-1-242-1000",
    email: "conor.murphy@example.ie",
    role: "provider",
    status: "active",
    location: "17 O'Connell Street, Dublin, D01 T9C2",
    image: "conor.murphy.jpg",
    rtn: "IE65432108701",
    otherInformation:
      "Conor Murphy works in a pharmaceutical company in Dublin.",
    createdAt: new Date("2024-02-07T23:35:52.087Z"),
    updatedAt: new Date("2024-02-07T23:38:03.259Z"),
  },
  {
    id: "4174f655-5cb2-4bd9-a785-ce11f16cebb0",
    userName: "Emma Tremblay",
    phone: "+1 604-555-0122",
    email: "emma.tremblay@example.com",
    role: "client",
    status: "inactive",
    location: "1020 Mainland Street, Vancouver, BC V6B 2T4",
    image: "emma.tremblay.jpg",
    rtn: "07081999021280",
    otherInformation:
      "Emma Tremblay is engaged in the environmental sector in Canada.",
    createdAt: new Date("2024-02-13T15:35:02.010Z"),
    updatedAt: new Date("2024-02-13T15:37:03.020Z"),
  },
  {
    id: "38d5126b-4473-40d2-8142-2e7049c07346",
    userName: "Maximilian Bauer",
    phone: "+49 30 567890",
    email: "maximilian.bauer@example.com",
    role: "client",
    status: "active",
    location: "Hauptstraße 5, 10178 Berlin",
    image: "maximilian.bauer.jpg",
    rtn: "08081999021280",
    otherInformation:
      "Maximilian Bauer works for an automobile company in Germany.",
    createdAt: new Date("2024-02-14T16:39:04.030Z"),
    updatedAt: new Date("2024-02-14T16:40:05.040Z"),
  },
  {
    id: "cb3ae8be-e376-4d26-9cfc-5884348c22ec",
    userName: "Sofia Ricci",
    phone: "+39 06 12345678",
    email: "sofia.ricci@example.com",
    role: "provider",
    status: "inactive",
    location: "Via Roma 15, 00184 Rome",
    image: "sofia.ricci.jpg",
    rtn: "09081999021280",
    otherInformation: "Sofia Ricci is part of the culinary field in Italy.",
    createdAt: new Date("2024-02-15T17:41:06.050Z"),
    updatedAt: new Date("2024-02-15T17:42:07.060Z"),
  },
  {
    id: "fa47c0f4-620c-40b3-a16a-b9afa9a88215",
    userName: "Arjun Patel",
    phone: "+91 22 2771 1234",
    email: "arjun.patel@example.com",
    role: "client",
    status: "active",
    location: "142 M.G. Road, Mumbai, Maharashtra 400001",
    image: "arjun.patel.jpg",
    rtn: "10081999021280",
    otherInformation:
      "Arjun Patel is active in the software industry in India.",
    createdAt: new Date("2024-02-16T18:43:08.070Z"),
    updatedAt: new Date("2024-02-16T18:44:09.080Z"),
  },
  {
    id: "8ce5b4d9-5182-4cbf-9d48-f187b377e931",
    userName: "Sato Yuki",
    phone: "+81 3 3541 1234",
    email: "sato.yuki@example.com",
    role: "client",
    status: "inactive",
    location: "2-11-3 Meguro, Tokyo 153-0063",
    image: "sato.yuki.jpg",
    rtn: "11081999021280",
    otherInformation:
      "Sato Yuki is engaged in the electronics sector in Japan.",
    createdAt: new Date("2024-02-17T19:45:10.090Z"),
    updatedAt: new Date("2024-02-17T19:46:11.100Z"),
  },
  {
    id: "cb2c15c3-7fc9-4d51-8b7b-3e636ac6195b",
    userName: "Lucas Silva",
    phone: "+55 11 9988-7766",
    email: "lucas.silva@example.com",
    role: "provider",
    status: "active",
    location: "Rua Oscar Freire, 379, São Paulo, SP 01426-001",
    image: "lucas.silva.jpg",
    rtn: "12081999021280",
    otherInformation:
      "Lucas Silva works in the agricultural business in Brazil.",
    createdAt: new Date("2024-02-18T20:47:12.110Z"),
    updatedAt: new Date("2024-02-18T20:48:13.120Z"),
  },
];

export const library: Library[] = [
  {
    id: "title1",
    slug: "tong-quan-ve-ma-tuy",
    title: "Tổng Quan Về Ma Túy",
    icon: card_image_1,
    subtitle: [
      {
        id: "subTitle1",
        title: "Định nghĩa",
        content: [
          "Theo khoản 1 Điều 2 Luật Phòng chống ma túy 2021 quy định chất ma túy là chất gây nghiện, chất hướng thần được quy định trong danh mục chất ma túy do Chính phủ ban hành.",
          "Theo đó, chất gây nghiện là chất kích thích hoặc ức chế thần kinh, dễ gây tình trạng nghiện đối với người sử dụng.",
          "Chất hướng thần là chất kích thích hoặc ức chế thần kinh hoặc gây ảo giác, nếu sử dụng nhiều lần có thể dẫn tới tình trạng nghiện đối với người sử dụng.",
        ],
        image: [""],
        imageDescription: [""],
      },
      {
        id: "subTitle2",
        title: "Phân loại",
        content: [
          "1. Theo nguồn gốc ",
          "Dựa vào nguồn gốc của ma tuý, có thể phân chia thành 3 loại: \n- Ma túy tự nhiên: Đây là các chất ma tuý có sẵn trong tự nhiên, là alcaloid của một số thực vật như cây thuốc phiện (anh túc), cây cần sa (cây gai dầu), cây coca (cocain). \n- Ma túy bán tổng hợp: Heroin, Moóc phin \n- Ma túy tổng hợp: Amphetamin, MDMA, ecstasy, ma túy đá...",
          "2. Phân loại theo tác động lên thần kinh trung ương",
          "- Nhóm gây ức chế hệ thần kinh trung ương: thuốc phiện, nguồn gốc thuốc phiện (morphin, heroin, cocain...), các thuốc an thần gây ngủ (seduxen, phenobarbital) \n- Nhóm gây kích thích thần kinh trung ương: Nhóm này gồm amphetamin và các dẫn xuất. Khi sử dụng gây tăng hoạt động, tăng sinh lực, tăng nhịp tim, tăng hô hấp... \n- Nhóm gây ảo giác: Nhóm này gây thay đổi về nhận thức và môi trường xung quanh, nghe thấy những âm thanh không có thực. Bao gồm các loại như thuốc lắc, cần sa...",
          "3. Phân loại theo mức độ gây nghiện",
          "Phân loại theo mức độ gây nghiện \n- Ma tuý hiệu lực cao: Sử dụng liều nhỏ đã gây ra các thay đổi tâm sinh lý con người và có thể gây nghiện sau vài lần sử dụng. Gồm: Thuốc phiện, heroin, cocaine, amphetamin, ecstasy… \n- Ma tuý hiệu lực thấp: Là các chất phải dùng liều thật cao mới có thể tác động đến tâm sinh lý người sử dụng. Ví dụ: thuốc lá, thuốc lào...",
        ],
        image: [],
        imageDescription: ["Ma túy tự nhiên", "Ma tuý bán tổng hợp"],
      },
    ],
  },
  {
    id: "title2",
    slug: "tac-hay-cua-ma-tuy",
    title: "Tác Hại Của Ma Tuý",
    icon: card_image_2,
    subtitle: [
      {
        id: "subTitle1",
        title: "Ảnh hưởng đến sức khỏe",
        content: [
          "Sử dụng ma túy gây tổn thương nghiêm trọng đến các cơ quan chính như hệ thần kinh, tim mạch và phổi. Các chất ma túy có thể làm suy giảm chức năng não bộ, gây rối loạn trí nhớ và khả năng tập trung.",
          "Người nghiện ma túy thường có nguy cơ mắc các bệnh về tim mạch như nhồi máu cơ tim và đột quỵ. Đối với hệ hô hấp, việc hít hoặc hút các chất ma túy có thể làm tổn thương phổi và làm tăng nguy cơ ung thư phổi.",
          "Ngoài ra, sử dụng ma túy còn làm tăng khả năng mắc các bệnh lây truyền qua đường máu như HIV/AIDS do hành vi dùng chung kim tiêm.",
        ],
        image: [],
        imageDescription: [
          "Hệ thần kinh bị tổn thương do ma túy",
          "Sự ảnh hưởng của ma túy đến hệ tim mạch",
        ],
      },
      {
        id: "subTitle2",
        title: "Tác hại về mặt tâm lý",
        content: [
          "Ma túy có thể gây ra các rối loạn tâm thần nghiêm trọng, bao gồm loạn thần, ảo giác và mất kiểm soát hành vi. Sử dụng ma túy trong thời gian dài có thể dẫn đến sự suy giảm tinh thần và các vấn đề về hành vi.",
          "Người nghiện ma túy có xu hướng phát triển các triệu chứng lo âu, hoảng loạn và trầm cảm. Các chất ma túy cũng ảnh hưởng đến khả năng kiểm soát cảm xúc, dẫn đến hành vi bạo lực và tự gây thương tích.",
          "Việc mất kiểm soát hành vi và suy giảm khả năng nhận thức có thể khiến người nghiện dễ dấn thân vào các hoạt động bất hợp pháp và làm tổn hại đến các mối quan hệ xã hội.",
        ],
        image: [],
        imageDescription: [
          "Rối loạn tâm thần do tác động của ma túy",
          "Sự suy giảm nhận thức và hành vi của người nghiện",
        ],
      },
    ],
  },
  {
    id: "title3",
    slug: "cai-nghien-va-ho-tro",
    title: "Cai Nghiện Và Hỗ Trợ",
    icon: card_image_3,
    subtitle: [
      {
        id: "subTitle1",
        title: "Quá trình cai nghiện",
        content: [
          "Quá trình cai nghiện là hành trình gian nan giúp người nghiện phục hồi và từ bỏ ma túy. Quá trình này thường bao gồm các giai đoạn như cắt giảm liều, điều trị bằng thuốc và tham vấn tâm lý nhằm hỗ trợ người nghiện về mặt tinh thần.",
          "Trong giai đoạn cai nghiện, người nghiện có thể gặp các triệu chứng khó chịu như run rẩy, đổ mồ hôi, lo lắng và đau nhức cơ thể. Để giảm thiểu các triệu chứng này, y tế và gia đình cần phối hợp để tạo điều kiện tốt nhất cho người nghiện.",
          "Ngoài ra, việc hỗ trợ tâm lý và giúp người nghiện xây dựng lại các mối quan hệ xã hội là yếu tố quan trọng để ngăn ngừa tái nghiện.",
        ],
        image: [],
        imageDescription: [],
      },
      {
        id: "subTitle2",
        title: "Vai trò của gia đình và cộng đồng",
        content: [
          "Gia đình đóng vai trò rất quan trọng trong việc hỗ trợ người nghiện phục hồi. Sự ủng hộ từ gia đình có thể giúp người nghiện có thêm động lực để từ bỏ ma túy và đối mặt với các khó khăn trong quá trình cai nghiện.",
          "Cộng đồng cũng có thể góp phần vào quá trình phục hồi của người nghiện thông qua các chương trình giáo dục và hỗ trợ tái hòa nhập. Các tổ chức cộng đồng và hội đoàn có thể cung cấp các hoạt động xã hội, giúp người nghiện làm quen với một cuộc sống lành mạnh.",
          "Các dịch vụ tư vấn và giáo dục cộng đồng là cần thiết để nâng cao nhận thức, giảm kỳ thị và tạo môi trường thân thiện cho người nghiện tái hòa nhập.",
        ],
        image: [],
        imageDescription: [],
      },
    ],
  },
  {
    id: "title4",
    slug: "hotline-ho-tro-khan-cap",
    title: "Hotline Hỗ Trợ Khẩn Cấp",
    icon: card_image_4,
    subtitle: [
      {
        id: "subTitle1",
        title: "Hotline tư vấn",
        content: [
          "Hotline hỗ trợ khẩn cấp hoạt động 24/7 nhằm cung cấp hỗ trợ nhanh chóng cho người gặp vấn đề về ma túy. Người nghiện hoặc người thân có thể gọi để được tư vấn và hỗ trợ giải quyết các tình huống khẩn cấp liên quan đến ma túy.",
          "Ngoài việc cung cấp thông tin về các trung tâm cai nghiện và các phương pháp điều trị, hotline còn hỗ trợ về mặt tâm lý cho người nghiện và gia đình họ, giúp họ có thể đưa ra quyết định đúng đắn trong quá trình cai nghiện.",
          "Hotline cũng là nơi người dân có thể báo cáo các hoạt động liên quan đến buôn bán và sử dụng trái phép ma túy trong cộng đồng, góp phần giúp cơ quan chức năng có thể can thiệp kịp thời.",
        ],
        image: [],
        imageDescription: [],
      },
      {
        id: "subTitle2",
        title: "Tư vấn pháp lý",
        content: [
          "Ngoài việc tư vấn về cai nghiện, hotline còn cung cấp các thông tin pháp lý cho người dân về quyền và trách nhiệm của họ liên quan đến ma túy. Điều này bao gồm các quyền lợi pháp lý khi tham gia vào các chương trình cai nghiện tự nguyện và những điều cần biết về luật pháp liên quan đến ma túy.",
          "Hotline cũng giúp người dân hiểu rõ các hình phạt liên quan đến hành vi tàng trữ, buôn bán và sử dụng ma túy, từ đó nâng cao ý thức tuân thủ pháp luật.",
          "Đội ngũ tư vấn pháp lý trên hotline luôn sẵn sàng hỗ trợ các thắc mắc liên quan đến pháp luật và bảo vệ quyền lợi hợp pháp của người dân khi tham gia các hoạt động phòng chống ma túy.",
        ],
        image: [],
        imageDescription: [],
      },
    ],
  },
];
