"use client";

import { Organization } from "./types";

export const organizations: Organization[] = [
  {
    id: "1",
    name: "FPT University",
    password: "securepass123",
    email: "fptuniversity@fpt.edu.vn",
    province: "Đà Nẵng",
    image: "/placeholder.svg?height=100&width=100",
    description:
      "Trường đại học dẫn đầu trong việc cung cấp các giải pháp sáng tạo.",
  },
  {
    id: "2",
    name: "Đại Học Khoa Học",
    password: "techpass456",
    email: "daihockhoahoc@gmail.com",
    province: "Thừa Thiên Huế",
    image: "/placeholder.svg?height=100&width=100",
    description:
      "Cung cấp nền tảng công nghệ hiện đại để phát triển giáo dục và nghiên cứu.",
  },
  {
    id: "3",
    name: "Đại học Văn Lang",
    password: "langpass789",
    email: "daihocvanlang@gmail.com",
    province: "Hồ Chí Minh",
    image: "/placeholder.svg?height=100&width=100",
    description:
      "Nơi ươm mầm tài năng, góp phần xây dựng xã hội văn minh, hiện đại.",
  },
  {
    id: "4",
    name: "Đại học Bách Khoa",
    password: "bkpass234",
    email: "daihocbachkhoa@gmail.com",
    province: "Hà Nội",
    image: "/placeholder.svg?height=100&width=100",
    description:
      "Trường đại học uy tín với chương trình đào tạo kỹ thuật hàng đầu.",
  },
  {
    id: "5",
    name: "Đại học Kỹ Thuật",
    password: "ktpass567",
    email: "daihockythuat@gmail.com",
    province: "Quảng Trị",
    image: "/placeholder.svg?height=100&width=100",
    description:
      "Đào tạo nguồn nhân lực chất lượng cao, đáp ứng nhu cầu phát triển công nghiệp.",
  },
  {
    id: "6",
    name: "Đại học Sư Phạm",
    password: "spass321",
    email: "daihocsupham@gmail.com",
    province: "Hải Phòng",
    image: "/placeholder.svg?height=100&width=100",
    description:
      "Tiên phong trong đào tạo giáo viên và các chuyên ngành khoa học cơ bản.",
  },
  {
    id: "7",
    name: "Đại học Y Dược",
    password: "ymedpass654",
    email: "daihocyduoc@gmail.com",
    province: "Cần Thơ",
    image: "/placeholder.svg?height=100&width=100",
    description:
      "Nâng cao chất lượng y tế và đào tạo chuyên gia chăm sóc sức khỏe cộng đồng.",
  },
  {
    id: "8",
    name: "Đại học Kinh Tế Quốc Dân",
    password: "ktqdp789",
    email: "ktqd@gmail.com",
    province: "Hà Nội",
    image: "/placeholder.svg?height=100&width=100",
    description:
      "Cung cấp các chương trình đào tạo kinh tế chuyên sâu và sáng tạo.",
  },
  {
    id: "9",
    name: "Đại học Tôn Đức Thắng",
    password: "tdtpass111",
    email: "tonducthang@gmail.com",
    province: "Hồ Chí Minh",
    image: "/placeholder.svg?height=100&width=100",
    description: "Môi trường học tập hiện đại, hội nhập và sáng tạo.",
  },
  {
    id: "10",
    name: "Đại học Đà Lạt",
    password: "dlpass789",
    email: "daihocdalat@gmail.com",
    province: "Lâm Đồng",
    image: "/placeholder.svg?height=100&width=100",
    description:
      "Cơ sở đào tạo hàng đầu về nông nghiệp và môi trường tại miền Trung.",
  },
];

export const provinces = [
  "Hà Nội",
  "Hồ Chí Minh",
  "Đà Nẵng",
  "Hải Phòng",
  "Cần Thơ",
  "An Giang",
  "Bà Rịa - Vũng Tàu",
  "Bắc Giang",
  "Bắc Kạn",
  "Bạc Liêu",
  "Bắc Ninh",
  "Bến Tre",
  "Bình Định",
  "Bình Dương",
  "Bình Phước",
  "Bình Thuận",
  "Cà Mau",
  "Cao Bằng",
  "Đắk Lắk",
  "Đắk Nông",
  "Điện Biên",
  "Đồng Nai",
  "Đồng Tháp",
  "Gia Lai",
  "Hà Giang",
  "Hà Nam",
  "Hà Tĩnh",
  "Hải Dương",
  "Hậu Giang",
  "Hòa Bình",
  "Hưng Yên",
  "Khánh Hòa",
  "Kiên Giang",
  "Kon Tum",
  "Lai Châu",
  "Lâm Đồng",
  "Lạng Sơn",
  "Lào Cai",
  "Long An",
  "Nam Định",
  "Nghệ An",
  "Ninh Bình",
  "Ninh Thuận",
  "Phú Thọ",
  "Phú Yên",
  "Quảng Bình",
  "Quảng Nam",
  "Quảng Ngãi",
  "Quảng Ninh",
  "Quảng Trị",
  "Sóc Trăng",
  "Sơn La",
  "Tây Ninh",
  "Thái Bình",
  "Thái Nguyên",
  "Thanh Hóa",
  "Thừa Thiên Huế",
  "Tiền Giang",
  "Trà Vinh",
  "Tuyên Quang",
  "Vĩnh Long",
  "Vĩnh Phúc",
  "Yên Bái",
];
