name: Cleanup PR Preview

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: read
  pull-requests: write

env:
  BASE_PORT: 3100

jobs:
  cleanup-preview:
    runs-on: ubuntu-22.04

    steps:
      - name: Get PR Info
        id: pr_info
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PREVIEW_PORT=$((BASE_PORT + PR_NUMBER))
          PREVIEW_URL="safe-edu-pr-${PR_NUMBER}.safe-edu.site"

          echo "pr_number=${PR_NUMBER}" >> $GITHUB_OUTPUT
          echo "preview_port=${PREVIEW_PORT}" >> $GITHUB_OUTPUT
          echo "preview_url=${PREVIEW_URL}" >> $GITHUB_OUTPUT

          echo "🧹 Cleaning up PR #${PR_NUMBER}"

      - name: Decode SSH key
        run: |
          echo "${{ secrets.VPS_SSH_KEY_BASE64 }}" | base64 -d > id_ed25519
          chmod 600 id_ed25519

      - name: Stop and Remove Preview Container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          port: ${{ secrets.VPS_PORT }}
          key_path: id_ed25519
          script: |
            echo "🛑 Stopping preview container for PR #${{ steps.pr_info.outputs.pr_number }}..."
            docker stop safe-edu-pr-${{ steps.pr_info.outputs.pr_number }} || true
            docker rm safe-edu-pr-${{ steps.pr_info.outputs.pr_number }} || true

            echo "🗑️ Removing preview image..."
            docker rmi ghcr.io/${{ github.repository_owner }}/safe-edu-front-end:pr-${{ steps.pr_info.outputs.pr_number }} || true

            echo "🗑️ Removing preview environment file..."
            rm -f /root/safe-edu-front-end/.env.pr-${{ steps.pr_info.outputs.pr_number }} || true

            echo "✅ Container and image removed!"

      - name: Remove Nginx Configuration
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          port: ${{ secrets.VPS_PORT }}
          key_path: id_ed25519
          script: |
            echo "🔧 Removing Nginx configuration..."
            rm -f /etc/nginx/sites-available/safe-edu-pr-${{ steps.pr_info.outputs.pr_number }} || true
            rm -f /etc/nginx/sites-enabled/safe-edu-pr-${{ steps.pr_info.outputs.pr_number }} || true

            echo "🔄 Testing and reloading Nginx..."
            if nginx -t 2>/dev/null; then
              systemctl reload nginx && echo "✅ Nginx reloaded successfully"
            else
              echo "⚠️  Nginx config test failed, but continuing cleanup"
            fi

            echo "✅ Nginx configuration cleanup completed!"

      - name: Comment Cleanup Status
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = ${{ steps.pr_info.outputs.pr_number }};
            const previewUrl = `safe-edu-pr-${prNumber}.safe-edu.site`;

            const body = `## 🧹 Preview Environment Cleaned Up

            The preview deployment has been removed:

            - **Preview URL**: ~~http://${previewUrl}~~ (no longer available)
            - **Container**: \`safe-edu-pr-${prNumber}\` (removed)

            ---
            🤖 *Cleaned up by GitHub Actions*`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: body,
            });
