name: Deploy to VPS - Log in to GHCR

on:
  workflow_call:

jobs:
  login-ghcr:
    runs-on: ubuntu-22.04
    steps:
      - name: Decode SSH key
        run: |
          echo "${{ secrets.VPS_SSH_KEY_BASE64 }}" | base64 -d > id_ed25519
          chmod 600 id_ed25519

      - name: Log in to GHCR
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          port: ${{ secrets.VPS_PORT }}
          key_path: id_ed25519
          script: |
            echo "🔐 Logging in to GHCR..."
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin