name: Deploy to VPS - Start App Container

on:
  workflow_call:

jobs:
  build-start-app:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Decode SSH key
        run: |
          echo "${{ secrets.VPS_SSH_KEY_BASE64 }}" | base64 -d > id_ed25519
          chmod 600 id_ed25519

      - name: Start Safe Edu app container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          port: ${{ secrets.VPS_PORT }}
          key_path: id_ed25519
          script: |
            echo "🚀 Starting Safe Edu app container..."
            docker rm -f safe-edu-frontend || true

            docker run -d \
              --name safe-edu-frontend \
              --env-file /root/safe-edu-front-end/.env \
              --network safe-edu-network \
              -p 3002:3002 \
              ghcr.io/${{ github.repository_owner }}/safe-edu-front-end:latest

            echo "⏳ Waiting 5s for container to initialize..."
            sleep 5

            echo "🔧 Monitoring application startup logs until ready..."

            attempts=0
            max_attempts=100

            until docker logs safe-edu-frontend 2>&1 | grep -q "Ready in"; do
              if [ "$attempts" -ge "$max_attempts" ]; then
                echo "❌ Reached maximum attempts ($max_attempts). The application did not become ready."
                docker logs safe-edu-frontend --tail 50
                exit 1
              fi

              echo "⏳ Still waiting for the app to be ready... ($((attempts + 1))/$max_attempts)"
              attempts=$((attempts + 1))
              sleep 20
            done

            echo "✅ Application is ready!"

            echo "📜 Final container logs:"
            docker logs safe-edu-frontend --tail 30