name: Setup SSH Key

on:
  workflow_call:

jobs:
  setup-ssh:
    runs-on: ubuntu-22.04

    steps:
      - name: Decode SSH key
        run: |
          echo "${{ secrets.VPS_SSH_KEY_BASE64 }}" | base64 -d > id_ed25519
          chmod 600 id_ed25519
          head -n 5 id_ed25519
          ls -l id_ed25519
          file id_ed25519